modules_dir = "artifacts/"

[[module]]
name = "ipfs_adapter"
max_heap_size = "2 MiB"
logger_enabled = true

[module.mounted_binaries]
ipfs = "/usr/local/bin/ipfs"

[[module]]
name = "ipfs_cli"
max_heap_size = "2 MiB"
logger_enabled = true
